# Python Quickstart

- 김병천 (wizardbc@gmail.com)
- 2023년 10월 27일 (금), 30일 (월)

Tutorial from [programiz.com](https://www.programiz.com/python-programming/tutorial)

In [ ]:
print("Hello, World!")

## Variables and Literals

* `=` means assign.

`a=5` means assign the numeric literal `5` to the variable `a`.

`a="Five"` means assign the string literal `"Five"` to the variable `a`.

In [ ]:
a = 5
print("a =", a)

In [ ]:
a = "Five"
print("a =", a)

## Operators

In [ ]:
x = 14
y = 4

# Add two operands
print('x + y =', x+y) # Output: x + y = 18

# Subtract right operand from the left
print('x - y =', x-y) # Output: x - y = 10

# Multiply two operands
print('x * y =', x*y) # Output: x * y = 56

# Divide left operand by the right one 
print('x / y =', x/y) # Output: x / y = 3.5

# Floor division (quotient) 몫
print('x // y =', x//y) # Output: x // y = 3

# Remainder of the division of left operand by the right
print('x % y =', x%y) # Output: x % y = 2

# Left operand raised to the power of right (x^y)
print('x ** y =', x**y) # Output: x ** y = 38416

In [ ]:
x = 5

# x += 5 ----> x = x + 5
x += 5
print(x) # Output: 10

# x /= 5 ----> x = x / 5
x /= 5
print(x) # Output: 2.0

In [ ]:
x *= 5

In [ ]:
x

## Type Conversion

### Implicit Type Conversion

In [ ]:
num_int = 123  # integer type
num_flo = 1.23 # float type

num_new = num_int + num_flo

print("Value of num_new:",num_new)
print("datatype of num_new:",type(num_new))

In [ ]:
num_int = 123     # int type
num_str = "456"   # str type

print(num_int+num_str)

### Explicit Type Conversion

In [ ]:
num_int = 123  # int type
num_str = "456" # str type

# explicitly converted to int type
num_str = int(num_str) 

print(num_int+num_str)

## Numeric Types

In [ ]:
# Output: <class 'int'>
print(type(5))

# Output: <class 'float'>
print(type(5.0))

c = 5 + 3j

# Output: <class 'complex'>
print(type(c))

# complex number i
print(1j)

### Boolean Types
- `and` operation

| and | T | F |
|-----|---|---|
| T   | T | F |
| F   | F | F |
- `or` operation

| or | T | F |
|-----|---|---|
| T   | T | T |
| F   | T | F |

In [ ]:
print(type(True))

print(True and True)  # True
print(False and True) # False

print(True or False)  # True

## Data Structures

### List

In [ ]:
# empty list
my_list = []
my_list = list()

# list of integers
my_list = [1, 2, 3]

# list with mixed data types
my_list = [1, "Hello", 3.4]

In [ ]:
language = ["French", "German", "English", "Polish"]

In [ ]:
# Accessing first element
print(language[0])

In [ ]:
language[-1]

In [ ]:
# Accessing fourth element
print(language[3])

# Accessing fourth element
print(language[-1])

# Get sub list (slice)
print(language[1:3])

In [ ]:
language[1:3] = ['Korean']
print(language)

### Tuples

Basically, lists are mutable whereas tuples are immutable.

In [ ]:
language = ("French", "German", "English", "Polish")
print(language)

print(language[1]) #Output: German
print(language[3]) #Output: Polish
print(language[-1]) # Output: Polish

In [ ]:
language[1:3] = ['Korean']
print(language)

### Strings

In [ ]:
# all of the following are equivalent
my_string = 'Hello'
print(my_string)

my_string = "Hello"
print(my_string)

my_string = '''Hello'''
print(my_string)

# triple quotes string can extend multiple lines
my_string = """Hello, welcome to
           the world of Python"""
print(my_string)

In [ ]:
# Hello, "World"!!!
print('Hello, "World"!!!')

In [ ]:
str = 'Mathematics'
print('str = ', str)

print('str[0] = ', str[0]) # Output: M

print('str[-1] = ', str[-1]) # Output: s

# slicing 2nd to 5th character
print('str[1:5] = ', str[1:5]) # Output: athe

# slicing 6th to 2nd last character
print('str[5:-2] = ', str[5:-2]) # Output: mati

In [ ]:
str1 = 'Hello '
str2 ='World!'

# Output: Hello World!
print(str1 + str2)

# Hello Hello Hello
print(str1 * 3)

### Sets

In [ ]:
my_set = set()

# set of integers
my_set = {1, 2, 3}
print(my_set)

# set of mixed datatypes
my_set = {1.0, "Hello", (1, 2, 3)}
print(my_set)

In [ ]:
# set of integers
my_set = {1, 2, 3}

my_set.add(4)
print(my_set) # Output: {1, 2, 3, 4}

my_set.add(2)
print(my_set) # Output: {1, 2, 3, 4}

my_set.update([3, 4, 5])
print(my_set) # Output: {1, 2, 3, 4, 5}

my_set.remove(4)
print(my_set) # Output: {1, 2, 3, 5}

In [ ]:
A = {1, 2, 3}
B = {2, 3, 4, 5}

# Equivalent to A.union(B) 
# Also equivalent to B.union(A)
print(A | B) # Output: {1, 2, 3, 4, 5}

# Equivalent to A.intersection(B)
# Also equivalent to B.intersection(A)
print (A & B) # Output: {2, 3}

# Set Difference
print (A - B) # Output: {1}

# Set Symmetric Difference
print(A ^ B)  # Output: {1, 4, 5}

## Dictionaries

In [ ]:
# empty dictionary
# my_dict = dict()
my_dict = {}

# dictionary with integer keys
my_dict = {1: 'apple', 2: 'ball'}

# dictionary with mixed keys
my_dict = {'name': 'John', 1: [2, 4, 3]}

In [ ]:
person = {'name':'Jack', 'age': 26}

# Changing age to 36
person['age'] = 36 
print(person) # Output: {'name': 'Jack', 'age': 36}

# Adding salary key, value pair
person['salary'] = 4342.4
print(person) # Output: {'name': 'Jack', 'age': 36, 'salary': 4342.4}


# Deleting age
del person['age']
print(person) # Output: {'name': 'Jack', 'salary': 4342.4}

# Deleting entire dictionary
del person

### Python `range()`

In [ ]:
print(range(1, 10)) # Output: range(1, 10)

In [ ]:
numbers = range(1, 6) # [1,6) = [1,5]

print(list(numbers)) # Output: [1, 2, 3, 4, 5]
print(tuple(numbers)) # Output: (1, 2, 3, 4, 5)
print(set(numbers)) # Output: {1, 2, 3, 4, 5}

In [ ]:
# Equivalent to: numbers = range(1, 6)
numbers1 = range(1, 6 , 1)
print(list(numbers1)) # Output: [1, 2, 3, 4, 5]

numbers2 = range(1, 6, 2)
print(list(numbers2)) # Output: [1, 3, 5]

numbers3 = range(5, 0, -1)
print(list(numbers3)) # Output: [5, 4, 3, 2, 1]

## Control Flow

### if...else Statement

In [ ]:
num = 1

if num > 0:
  print("Positive number")
elif num == 0:
  print("Zero")
else:
  print("Negative number")
    
# Output: Negative number

In [ ]:
if False:
  print("I am inside the body of if.")
  print("I am also inside the body of if.")
print("I am outside the body of if")

# Output: I am outside the body of if.

In [ ]:
bool([])

In [ ]:
a = ''

In [ ]:
if a:
  print(a)
else:
  a += 'a'

### while Loop

In [ ]:
n = 100

# initialize sum and counter
sum = 0
i = 1

while i <= n:
  sum += i
  i += 1    # update counter

print("The sum is", sum)

# Output: The sum is 5050

### for Loop

In [ ]:
numbers = [6, 5, 3, 8, 4, 2]

sum = 0

# iterate over the list
for val in numbers:
  sum += val

print("The sum is", sum) # Output: The sum is 28

In [ ]:
for val in "Mathematics":
    if val == "f":
        break
    print(val)
else:
  print("The end")


In [ ]:
for val in "Mathematics":
    if val == "e":
        continue
    print(val)
else:
  print("The end")

In [ ]:
a = []

if not a:
  raise NotImplementedError
else:
  print(a)


In [ ]:
# IndentationError: expected an indented block
for val in "Mathematics":
else:
  print("The end")

In [ ]:
for val in "Mathematics":
  pass
else:
  print("The end")

### Function

In [ ]:
def print_lines():
  print("I am line1.")
  print("I am line2.")

# function call
print_lines()

In [ ]:
def add_numbers(a, b):
  sum = a + b
  return sum

result = add_numbers(4, 5)
print(result)
# Output: 9

### Decorator
- A Function that returns a (modified) function.

In [ ]:
def one_more(ftn):
  def wrapper(a, b):
    return ftn(a,b)+1
  return wrapper

one_more(add_numbers)(4, 5)

In [ ]:
@one_more
def add_numbers_one_more(a, b):
  sum = a + b
  return sum

add_numbers_one_more(4,5)

In [ ]:
def more(n):
  def outer(ftn):
    def inner(a,b):
      return ftn(a,b)+n
    return inner
  return outer

more(10)(add_numbers)(4,5)

In [ ]:
@more(10)
def add_numbers_ten_more(a,b):
  return a + b

add_numbers_ten_more(4,5)

### Lambda Function

In [ ]:
def square(x):
  return x**2
print(square(5))

In [ ]:
square = lambda x: x ** 2
print(square(5))

# Output: 25

In [ ]:
numbers = [6, 5, 3, 8, 4, 2]
numbers2 = map(lambda x: x ** 2, numbers)

In [ ]:
list(numbers2)

In [ ]:
numbers_lt_5 = filter(lambda x: x<5, numbers)
print(list(numbers_lt_5))

In [ ]:
res = []
for i in numbers:
  if i < 5:
    res.append(i)
res

### Generators

In [ ]:
# A simple generator function
def my_gen():
  n = 1
  print('This is printed first')
  # Generator function contains yield statements
  yield n

  n += 1
  print('This is printed second')
  yield n

  n += 1
  print('This is printed at last')
  yield n

In [ ]:
# It returns an object but does not start execution immediately.
a = my_gen()

In [ ]:
a

In [ ]:
# We can iterate through the items using next().
print(next(a))  # 1

In [ ]:
# Once the function yields, the function is paused and the control is transferred to the caller.
# Local variables and theirs states are remembered between successive calls.
print(next(a)) # 2

print(next(a)) # 3

In [ ]:
# Finally, when the function terminates, StopIteration is raised automatically on further calls.
print(next(a))

In [ ]:
# Using for loop
for item in my_gen():
  print(item)
  break
else:
  print("End")

In [ ]:
def bad_generator():
  while True:
    yield 1

# for i in bad_generator():
#   print(i)

## Comprehension

In [ ]:
# list comprehension
numbers = [6, 5, 3, 8, 4, 2]
print([x**2 for x in numbers])

In [ ]:
# generator expression
numbers = [6, 5, 3, 8, 4, 2]
print((x**2 for x in numbers))

In [ ]:
for i in (x**2 for x in numbers):
  print(i)

## Class

In [1]:
class MyClass():
  def __init__(self, a):
    self.a = a
  def add(self, b):
    self.a = self.a + b
    return self

In [2]:
obj1 = MyClass(10)
print(obj1.a)

10


In [3]:
obj1.add(8)

In [4]:
print(obj1.a)

18


In [6]:
obj2 = MyClass(15)
obj2.a

15

In [7]:
obj1.a

18

In [8]:
obj2.a

15

In [9]:
class MyClass2(MyClass):
  def mul(self, b):
    self.a = self.a * b
    return self

In [10]:
obj3 = MyClass2(10)
print(obj3.a)

10


In [11]:
obj3.mul(3)
print(obj3.a)

30


In [12]:
obj3.add(5).mul(2).add(3)
print(obj3.a)

73


### Annotation

In [13]:
class MyClass():
  a: float
  def __init__(self, a:float):
    self.a = a
  def add(self, b:float):
    self.a += b
    return self

In [15]:
obj = MyClass(3.0)
print(obj.a)
obj.add(2.0).add(3.0)
print(obj.a)

3.0
8.0


* Annotation is NOT static typing.

In [16]:
obj = MyClass(3)
print(obj.a)
obj.add(2).add(3)
print(obj.a)

3
8


In [19]:
obj = MyClass('3')
obj.add('6')

In [20]:
obj.a

'36'

# NumPy Quickstart

[NumPy User Guide](https://numpy.org/doc/stable/user/absolute_beginners.html)

```bash
conda activate MathAI
pip install numpy
```

In [1]:
import numpy as np

## Shape of an array

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).



In [2]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [3]:
array_example.ndim

3

In [4]:
array_example.size

24

In [5]:
array_example.shape

(3, 2, 4)

In [10]:
np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]], dtype=np.float32)

array([[[0., 1., 2., 3.],
        [4., 5., 6., 7.]],

       [[0., 1., 2., 3.],
        [4., 5., 6., 7.]],

       [[0., 1., 2., 3.],
        [4., 5., 6., 7.]]], dtype=float32)

In [11]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [14]:
ex_list = [[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]]
ex_list

[[[0, 1, 2, 3], [4, 5, 6, 7]],
 [[0, 1, 2, 3], [4, 5, 6, 7]],
 [[0, 1, 2, 3], [4, 5, 6, 7]]]

In [16]:
[[[x * 3 for x in a] for a in b] for b in ex_list]

[[[0, 3, 6, 9], [12, 15, 18, 21]],
 [[0, 3, 6, 9], [12, 15, 18, 21]],
 [[0, 3, 6, 9], [12, 15, 18, 21]]]

In [18]:
array_example * 3

array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21]],

       [[ 0,  3,  6,  9],
        [12, 15, 18, 21]],

       [[ 0,  3,  6,  9],
        [12, 15, 18, 21]]])

In [19]:
array_example.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
       6, 7])

In [21]:
array_example.reshape(3, 2, 2, 2)

array([[[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]],


       [[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]],


       [[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]]])

## Indexing and Slicing

In [22]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [23]:
array_example[1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array_example[1, 0, 0]

0

In [25]:
array_example[1,:,1:3]

array([[1, 2],
       [5, 6]])

## Basic Array Operations

* Element-wise operations

In [26]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data, ones

(array([1, 2]), array([1, 1]))

In [27]:
data + ones

array([2, 3])

In [28]:
data - ones

array([0, 1])

In [30]:
data * data

array([1, 4])

In [31]:
data / data

array([1., 1.])

In [32]:
data ** 2

array([1, 4])

In [33]:
data + np.ones(3, dtype=int)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [34]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [35]:
sum(a)

10

In [39]:
b = np.array([[1, 1, 1], [2, 2, 2]])
b

array([[1, 1, 1],
       [2, 2, 2]])

In [40]:
b.shape

(2, 3)

In [41]:
b.sum(axis=0)

array([3, 3, 3])

In [42]:
b.sum(axis=0).shape

(3,)

In [43]:
b.sum(axis=1)

array([3, 6])

In [44]:
b.sum(axis=1).shape

(2,)

In [48]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
c.max(axis=1)

array([3, 6])

In [51]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [52]:
a.min(), a.max(), a.sum(), a.mean()

(0.05093587, 0.82485143, 4.8595784, 0.4049648666666667)

In [53]:
a.shape

(3, 4)

In [54]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

## Broadcasting

In [2]:
import numpy as np

In [3]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

Multiply scalar.

In [58]:
array_example * 3.0

array([[[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.]],

       [[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.]],

       [[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.]]])

Consider $\mathbb R^{3\times 2\times 4}$ as $((\mathbb R^4)^2)^3$-vector space.

An element of $\mathbb R^4$ is a scalar in $(\mathbb R^4)^2$ and $((\mathbb R^4)^2)^3$.

In [4]:
array_example.shape

(3, 2, 4)

In [5]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [6]:
np.array([0,1,2,3]).shape

(4,)

In [7]:
array_example * np.array([0,1,2,3])

array([[[ 0,  1,  4,  9],
        [ 0,  5, 12, 21]],

       [[ 0,  1,  4,  9],
        [ 0,  5, 12, 21]],

       [[ 0,  1,  4,  9],
        [ 0,  5, 12, 21]]])

In [9]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

We can re-order the powers, so $\mathbb R^{3\times 2\times 4}$ can be considered as $((\mathbb R^{2})^3)^4$.

So an element of $\mathbb R^2=\mathbb R^{1\times 2\times 1}$ is a scalar in $\mathbb R^{3\times 2\times 4}$.

In [8]:
array_example * np.array([2,3]).reshape((1,2,1))

array([[[ 0,  2,  4,  6],
        [12, 15, 18, 21]],

       [[ 0,  2,  4,  6],
        [12, 15, 18, 21]],

       [[ 0,  2,  4,  6],
        [12, 15, 18, 21]]])

In [10]:
(4) 

4

In [11]:
(4,)

(4,)

# Linear Algebra

## Matrix Product

In [12]:
A = np.random.rand(3,4)
B = np.random.rand(4,5)

In [13]:
A

array([[0.55043397, 0.07715091, 0.84301328, 0.78181968],
       [0.33221863, 0.62712744, 0.75747141, 0.31391294],
       [0.13668676, 0.69950565, 0.9875208 , 0.83269214]])

In [14]:
B

array([[0.61672884, 0.02101391, 0.58668263, 0.44393419, 0.63966184],
       [0.40665069, 0.16937113, 0.84580704, 0.64992677, 0.62358101],
       [0.06346374, 0.78829231, 0.82143235, 0.090632  , 0.38953952],
       [0.54049339, 0.19617   , 0.72181938, 0.48762796, 0.50394468]])

In [15]:
np.matmul(A,B)

array([[0.84691113, 0.84254436, 1.64499581, 0.75214002, 1.12258231],
       [0.67765046, 0.77188769, 1.57413567, 0.776794  , 1.05683215],
       [0.88148949, 1.06315266, 2.08407341, 1.01085234, 1.3279409 ]])

In [16]:
np.matmul(A,B).shape

(3, 5)

In [17]:
A@B

array([[0.84691113, 0.84254436, 1.64499581, 0.75214002, 1.12258231],
       [0.67765046, 0.77188769, 1.57413567, 0.776794  , 1.05683215],
       [0.88148949, 1.06315266, 2.08407341, 1.01085234, 1.3279409 ]])

In [18]:
x = np.random.rand(128,3,4)
W = np.random.rand(4,5)

In [19]:
np.matmul(x,W).shape

(128, 3, 5)